; INCLUDE\VIDEO.INC
; --- VIDEO.INC ---
; --- Salix16 Video Module ---
; ----------------------------
;   -- Video Text Module --
EXTRN Vid_Txt_Set_Mode:PROC
EXTRN Vid_Txt_Write_Char:PROC
EXTRN Vid_Txt_Write_String:PROC
EXTRN Vid_Txt_Clear_Screen:PROC
EXTRN Vid_Txt_Set_Attr:PROC
EXTRN Vid_Txt_Draw_HLine:PROC
EXTRN Vid_Txt_Draw_VLine:PROC
EXTRN Vid_Txt_Draw_Rect:PROC
EXTRN Vid_Txt_Draw_Box:PROC
EXTRN Vid_Txt_Draw_Border:PROC
EXTRN Vid_Txt_Draw_Panel:PROC
;--------------------------------