; INCLUDE\VIDEO.INC
; --- VIDEO.INC ---
; --- Salix16 Video Module ---
; ----------------------------
;   -- Video Text Module --
EXTRN Vid_Txt_Set_Mode:NEAR
EXTRN Vid_Txt_Write_Char:NEAR
EXTRN Vid_Txt_Write_String:NEAR
EXTRN Vid_Txt_Clear_Screen:NEAR
EXTRN Vid_Txt_Set_Attr:NEAR
EXTRN Vid_Txt_Draw_HLine:NEAR
EXTRN Vid_Txt_Draw_VLine:NEAR
EXTRN Vid_Txt_Draw_Rect:NEAR
EXTRN Vid_Txt_Draw_Box:NEAR
EXTRN Vid_Txt_Draw_Border:NEAR
EXTRN Vid_Txt_Draw_Panel:NEAR
;--------------------------------